-- ============================================================
-- Res. 424/2020 — botón de arrepentimiento: withdrawal_requests
-- ============================================================
-- Tabla de solicitudes de arrepentimiento del comprador, Edge
-- Function request-withdrawal (altas, solo service role) y RPC
-- admin_update_withdrawal (gestión del admin).
--
-- NO toca pedidos, pagos ni stock: cancelar el pedido y el
-- reembolso los gestiona el admin a mano (como hoy).
--
-- Idempotente: CREATE ... IF NOT EXISTS / CREATE OR REPLACE /
-- DROP POLICY IF EXISTS / REVOKE-GRANT seguros de repetir.
--
-- Verificado en remoto 2026-10-06:
--   * profiles NO tiene columna email -> el email de la cuenta
--     vive en auth.users.email (orders.user_id -> auth.users).
--   * "es admin" = is_admin() (SECURITY DEFINER, consulta
--     profiles.role = 'admin'), mismo mecanismo que el resto.
--   * numero_pedido es UNIQUE en orders (orders_numero_pedido_key).
-- ============================================================

-- ------------------------------------------------------------
-- 1. Secuencia propia para el número de constancia ARR-000001
--    (mismo patrón que order_number_seq / generate_order_number)
-- ------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public.withdrawal_number_seq
  START WITH 1 INCREMENT BY 1;

-- ------------------------------------------------------------
-- 2. Tabla
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.withdrawal_requests (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero          text        NOT NULL
                            DEFAULT ('ARR-' || LPAD(nextval('public.withdrawal_number_seq')::text, 6, '0')),
  order_id        integer     NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,
  user_id         uuid        NOT NULL,  -- snapshot de orders.user_id (sin FK: el registro legal no se borra)
  numero_pedido   text        NOT NULL,  -- snapshot de orders.numero_pedido
  nombre          text        NOT NULL CHECK (char_length(nombre) BETWEEN 2 AND 120),
  email           text        NOT NULL,  -- email de la cuenta al momento de pedirlo (snapshot)
  order_item_ids  integer[]       NULL,  -- NULL = todo el pedido
  motivo          text            NULL CHECK (motivo IS NULL OR char_length(motivo) <= 500),
  status          text        NOT NULL DEFAULT 'received'
                            CHECK (status IN ('received','in_progress','completed','rejected')),
  within_deadline boolean     NOT NULL,  -- solo informativo; nunca bloquea la solicitud
  admin_notes     text            NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  handled_at      timestamptz     NULL,
  handled_by      uuid            NULL,
  CONSTRAINT withdrawal_requests_numero_unique UNIQUE (numero)
);

-- ------------------------------------------------------------
-- 3. Índices
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_order_id
  ON public.withdrawal_requests (order_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_user_id
  ON public.withdrawal_requests (user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status
  ON public.withdrawal_requests (status);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_created_at
  ON public.withdrawal_requests (created_at DESC);

-- A lo sumo UNA solicitud abierta por pedido (defiende el chequeo
-- de "ya pediste" ante requests concurrentes: si dos altas pasan
-- juntas, la segunda recibe 23505 y la Edge Function devuelve la
-- existente con already_requested=true). Al cerrar la solicitud
-- (completed/rejected) el índice parcial deja libre el pedido.
CREATE UNIQUE INDEX IF NOT EXISTS idx_withdrawal_requests_open_per_order
  ON public.withdrawal_requests (order_id)
  WHERE status IN ('received','in_progress');

-- ------------------------------------------------------------
-- 4. RLS: solo SELECT (altas vía EF con service role;
--    cambios de estado vía RPC admin_update_withdrawal, SECURITY
--    DEFINER). NO hay policies de INSERT/UPDATE/DELETE.
-- ------------------------------------------------------------
ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;

-- El usuario ve solo las suyas (mismo patrón que orders_select_own)
DROP POLICY IF EXISTS "withdrawal_requests_select_own" ON public.withdrawal_requests;
CREATE POLICY "withdrawal_requests_select_own" ON public.withdrawal_requests
  FOR SELECT
  TO public
  USING (user_id = auth.uid());

-- El admin ve todas (mismo mecanismo admin que el resto: is_admin())
DROP POLICY IF EXISTS "withdrawal_requests_select_admin" ON public.withdrawal_requests;
CREATE POLICY "withdrawal_requests_select_admin" ON public.withdrawal_requests
  FOR SELECT
  TO authenticated
  USING (is_admin());

-- ------------------------------------------------------------
-- 5. RPC admin: admin_update_withdrawal(p_id, p_status, p_notes)
--    Misma estructura de verificación que update_payment_status:
--    auth.uid() obligatorio + is_admin() o 42501.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_update_withdrawal(
  p_id integer,
  p_status text,
  p_notes text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public
AS $function$
DECLARE
  v_user_id uuid;
  v_is_admin boolean;
  v_row public.withdrawal_requests%ROWTYPE;
BEGIN
  -- 1. Verificar usuario autenticado
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RAISE EXCEPTION 'No hay usuario autenticado';
  END IF;

  -- 2. Verificar rol admin (mismo código de error 42501 que
  --    update_payment_status / cancel_order)
  SELECT is_admin() INTO v_is_admin;
  IF NOT v_is_admin THEN
    RAISE EXCEPTION 'No autorizado: se requiere rol admin'
      USING ERRCODE = '42501';
  END IF;

  -- 3. Validar estado
  IF p_status IS NULL OR p_status NOT IN ('received','in_progress','completed','rejected') THEN
    RAISE EXCEPTION 'Estado de solicitud no reconocido: %', p_status;
  END IF;

  -- 4. Actualizar (siempre deja trazabilidad de quién y cuándo)
  UPDATE public.withdrawal_requests
  SET status = p_status,
      admin_notes = p_notes,
      handled_at = now(),
      handled_by = auth.uid()
  WHERE id = p_id
  RETURNING * INTO v_row;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Solicitud no encontrada: %', p_id;
  END IF;

  -- 5. Devolver la fila actualizada
  RETURN to_jsonb(v_row);
END;
$function$;

-- Mismo patrón de grants que update_payment_status / cancel_order:
-- REVOKE (anon, PUBLIC, postgres) + GRANT authenticated.
REVOKE EXECUTE ON FUNCTION public.admin_update_withdrawal(integer, text, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_withdrawal(integer, text, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_update_withdrawal(integer, text, text) FROM postgres;
GRANT EXECUTE ON FUNCTION public.admin_update_withdrawal(integer, text, text) TO authenticated;
